name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history including tags

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: python -m pip install poetry

    - name: Install poetry dynamic versioning tool
      run: python -m pip install poetry-dynamic-versioning

    - name: Fetch all tags
      run: git fetch --tags --force

    - name: Set dynamic version from latest tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest tag is: $latest_tag"
        poetry version $latest_tag
      shell: bash

    - name: Commit and push version bump
      run: |
        git config user.name "danielmlow"
        git config user.email "daniel.m.low@gmail.com"
        git commit -am "Bump version to $latest_tag"
        git push origin main
        git tag $latest_tag
        git push origin $latest_tag
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      shell: bash

    - name: Build package
      run: poetry build

    - name: Configure Poetry PyPI token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Publish to PyPI
      run: poetry publish --build --no-interaction
      env:
        POETRY_REQUESTS_TIMEOUT: 120