name: Auto-release

on:
  push:
    tags:
    - v*.*.*      # Only trigger on tags following the version pattern vX.X.X

env:
  AUTO_VERSION: v11.1.2

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare repository
      run: git fetch --unshallow --tags

    - name: Unset header
      run: git config --local --unset http.https://github.com/.extraheader

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Download auto
      run: |
        auto_download_url="$(curl -fsSL https://api.github.com/repos/intuit/auto/releases/tags/$AUTO_VERSION | jq -r '.assets[] | select(.name == "auto-linux.gz") | .browser_download_url')"
        wget -O- "$auto_download_url" | gunzip > ~/auto
        chmod a+x ~/auto

    - name: Create release
      run: |
        ~/auto shipit -vv
      env:
        GH_TOKEN: ${{ secrets.AUTO_ORG_TOKEN }}
