name: Auto-release

on:
  push:
    branches:
    - main

env:
  AUTO_VERSION: v11.1.2

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure Git User
      run: |
        git config --global user.email "daniel.m.low@gmail.com"
        git config --global user.name "danielmlow"

    - name: Prepare repository
      run: git fetch --unshallow --tags

    - name: Unset header
      run: git config --local --unset http.https://github.com/.extraheader

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download auto
      run: |
        auto_download_url="$(curl -fsSL https://api.github.com/repos/intuit/auto/releases/tags/$AUTO_VERSION | jq -r '.assets[] | select(.name == "auto-linux.gz") | .browser_download_url')"
        wget -O- "$auto_download_url" | gunzip > ~/auto
        chmod a+x ~/auto

    - name: Check if tag already exists
      id: check_tag
      run: |
        if git rev-parse "v1.0.7" >/dev/null 2>&1; then
          echo "Tag v1.0.7 already exists"
          exit 1
        fi

    - name: Create release
      if: steps.check_tag.outcome != 'failure'  # Only run if the tag doesn't exist
      run: |
        ~/auto shipit -vv
      env:
        GH_TOKEN: ${{ secrets.GH_Token }}