name: Auto-release

on:
  push:
    branches:
      - main

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Git User
        run: |
          git config --global user.email "daniel.m.low@gmail.com"
          git config --global user.name "danielmlow"

      - name: Auto Release
        uses: intuit/auto@v1
        with:
          github-token: ${{ secrets.GH_Token }}
          plugins: |
            python
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  # Include this if you're publishing to PyPI